[package]
name = "pijama"
version = "0.1.0"
authors = ["Christian Poveda <git@christianpoveda.xyz>"]
edition = "2018"

[dependencies]
nom = "5.1.1"
thiserror = "1.0"
lazy_static = "1.4.0"
either = "1.5.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "eval"
harness = false
