[package]
name = "pijama_parser"
version = "0.1.0"
authors = ["The Pijama Project Developres"]
edition = "2018"

[build-dependencies.lalrpop]
version = "0.19.0"

[dependencies]
thiserror = "1.0"
lalrpop-util = "0.19.0"
logos = "0.11.4"
pijama_ast = {path = "../pijama_ast"}
